---
gitian_user: vagrant
gitian_builder_url: "{{ lookup('env','GITIAN_BUILDER_URL') }}"
gitian_builder_version: "{{ lookup('env','GITIAN_BUILDER_VERSION') }}"
zcash_git_repo_url: https://github.com/zcash/zcash
zcash_gitian_sigs_repo: https://github.com/zcash/gitian.sigs
zcash_version: master
gitian_host_ip: 10.0.2.15
lxc_guest_ip: 10.0.3.5
zcash_developer_pubkeys:
  - name: nathan
    id: ED417FBE79C99E8C
  - name: daira
    id: 067F492098CF2762
  - name: sean
    id: 95684257D8F8B031
  - name: jack
    id: 0EC51FCDA94FB53E
